/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DownloadClientRouteImport } from './routes/download-client'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedVtcSlugRouteImport } from './routes/_authenticated/vtc.$slug'
import { Route as AuthenticatedDiscoverSlugRouteImport } from './routes/_authenticated/discover.$slug'
import { Route as AuthenticatedVtcSlugIndexRouteImport } from './routes/_authenticated/vtc.$slug.index'
import { Route as ApiPublicTelemetryLivemapRouteImport } from './routes/api/public/telemetry/livemap'
import { Route as ApiPublicTelemetryLiveRouteImport } from './routes/api/public/telemetry/live'
import { Route as ApiPublicTelemetryIngestRouteImport } from './routes/api/public/telemetry/ingest'
import { Route as ApiPublicMessagesSendRouteImport } from './routes/api/public/messages/send'
import { Route as ApiPublicMessagesListRouteImport } from './routes/api/public/messages/list'
import { Route as ApiPublicJobsRecentRouteImport } from './routes/api/public/jobs/recent'
import { Route as AuthenticatedVtcSlugVehiclesRouteImport } from './routes/_authenticated/vtc.$slug.vehicles'
import { Route as AuthenticatedVtcSlugTelemetryRouteImport } from './routes/_authenticated/vtc.$slug.telemetry'
import { Route as AuthenticatedVtcSlugStatsRouteImport } from './routes/_authenticated/vtc.$slug.stats'
import { Route as AuthenticatedVtcSlugSettingsRouteImport } from './routes/_authenticated/vtc.$slug.settings'
import { Route as AuthenticatedVtcSlugMessagesRouteImport } from './routes/_authenticated/vtc.$slug.messages'
import { Route as AuthenticatedVtcSlugLiveRouteImport } from './routes/_authenticated/vtc.$slug.live'
import { Route as AuthenticatedVtcSlugJobsRouteImport } from './routes/_authenticated/vtc.$slug.jobs'
import { Route as AuthenticatedVtcSlugFleetRouteImport } from './routes/_authenticated/vtc.$slug.fleet'
import { Route as AuthenticatedVtcSlugFinanceRouteImport } from './routes/_authenticated/vtc.$slug.finance'
import { Route as AuthenticatedVtcSlugEventsRouteImport } from './routes/_authenticated/vtc.$slug.events'
import { Route as AuthenticatedVtcSlugDriversRouteImport } from './routes/_authenticated/vtc.$slug.drivers'
import { Route as AuthenticatedVtcSlugDocumentsRouteImport } from './routes/_authenticated/vtc.$slug.documents'
import { Route as AuthenticatedVtcSlugCostsRouteImport } from './routes/_authenticated/vtc.$slug.costs'
import { Route as AuthenticatedVtcSlugCareerRouteImport } from './routes/_authenticated/vtc.$slug.career'
import { Route as AuthenticatedVtcSlugBillingRouteImport } from './routes/_authenticated/vtc.$slug.billing'
import { Route as AuthenticatedVtcSlugApplicationsRouteImport } from './routes/_authenticated/vtc.$slug.applications'
import { Route as AuthenticatedVtcSlugJobsIndexRouteImport } from './routes/_authenticated/vtc.$slug.jobs.index'
import { Route as AuthenticatedVtcSlugJobsNewRouteImport } from './routes/_authenticated/vtc.$slug.jobs.new'
import { Route as AuthenticatedVtcSlugJobsJobIdRouteImport } from './routes/_authenticated/vtc.$slug.jobs.$jobId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadClientRoute = DownloadClientRouteImport.update({
  id: '/download-client',
  path: '/download-client',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVtcSlugRoute = AuthenticatedVtcSlugRouteImport.update({
  id: '/vtc/$slug',
  path: '/vtc/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverSlugRoute =
  AuthenticatedDiscoverSlugRouteImport.update({
    id: '/discover/$slug',
    path: '/discover/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVtcSlugIndexRoute =
  AuthenticatedVtcSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVtcSlugRoute,
  } as any)
const ApiPublicTelemetryLivemapRoute =
  ApiPublicTelemetryLivemapRouteImport.update({
    id: '/api/public/telemetry/livemap',
    path: '/api/public/telemetry/livemap',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelemetryLiveRoute = ApiPublicTelemetryLiveRouteImport.update({
  id: '/api/public/telemetry/live',
  path: '/api/public/telemetry/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelemetryIngestRoute =
  ApiPublicTelemetryIngestRouteImport.update({
    id: '/api/public/telemetry/ingest',
    path: '/api/public/telemetry/ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMessagesSendRoute = ApiPublicMessagesSendRouteImport.update({
  id: '/api/public/messages/send',
  path: '/api/public/messages/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMessagesListRoute = ApiPublicMessagesListRouteImport.update({
  id: '/api/public/messages/list',
  path: '/api/public/messages/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsRecentRoute = ApiPublicJobsRecentRouteImport.update({
  id: '/api/public/jobs/recent',
  path: '/api/public/jobs/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVtcSlugVehiclesRoute =
  AuthenticatedVtcSlugVehiclesRouteImport.update({
    id: '/vehicles',
    path: '/vehicles',
    getParentRoute: () => AuthenticatedVtcSlugRoute,
  } as any)
const AuthenticatedVtcSlugTelemetryRoute =
  AuthenticatedVtcSlugTelemetryRouteImport.update({
    id: '/telemetry',
    path: '/telemetry',
    getParentRoute: () => AuthenticatedVtcSlugRoute,
  } as any)
const AuthenticatedVtcSlugStatsRoute =
  AuthenticatedVtcSlugStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AuthenticatedVtcSlugRoute,
  } as any)
const AuthenticatedVtcSlugSettingsRoute =
  AuthenticatedVtcSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedVtcSlugRoute,
  } as any)
const AuthenticatedVtcSlugMessagesRoute =
  AuthenticatedVtcSlugMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedVtcSlugRoute,
  } as any)
const AuthenticatedVtcSlugLiveRoute =
  AuthenticatedVtcSlugLiveRouteImport.update({
    id: '/live',
    path: '/live',
    getParentRoute: () => AuthenticatedVtcSlugRoute,
  } as any)
const AuthenticatedVtcSlugJobsRoute =
  AuthenticatedVtcSlugJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedVtcSlugRoute,
  } as any)
const AuthenticatedVtcSlugFleetRoute =
  AuthenticatedVtcSlugFleetRouteImport.update({
    id: '/fleet',
    path: '/fleet',
    getParentRoute: () => AuthenticatedVtcSlugRoute,
  } as any)
const AuthenticatedVtcSlugFinanceRoute =
  AuthenticatedVtcSlugFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedVtcSlugRoute,
  } as any)
const AuthenticatedVtcSlugEventsRoute =
  AuthenticatedVtcSlugEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedVtcSlugRoute,
  } as any)
const AuthenticatedVtcSlugDriversRoute =
  AuthenticatedVtcSlugDriversRouteImport.update({
    id: '/drivers',
    path: '/drivers',
    getParentRoute: () => AuthenticatedVtcSlugRoute,
  } as any)
const AuthenticatedVtcSlugDocumentsRoute =
  AuthenticatedVtcSlugDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedVtcSlugRoute,
  } as any)
const AuthenticatedVtcSlugCostsRoute =
  AuthenticatedVtcSlugCostsRouteImport.update({
    id: '/costs',
    path: '/costs',
    getParentRoute: () => AuthenticatedVtcSlugRoute,
  } as any)
const AuthenticatedVtcSlugCareerRoute =
  AuthenticatedVtcSlugCareerRouteImport.update({
    id: '/career',
    path: '/career',
    getParentRoute: () => AuthenticatedVtcSlugRoute,
  } as any)
const AuthenticatedVtcSlugBillingRoute =
  AuthenticatedVtcSlugBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedVtcSlugRoute,
  } as any)
const AuthenticatedVtcSlugApplicationsRoute =
  AuthenticatedVtcSlugApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedVtcSlugRoute,
  } as any)
const AuthenticatedVtcSlugJobsIndexRoute =
  AuthenticatedVtcSlugJobsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVtcSlugJobsRoute,
  } as any)
const AuthenticatedVtcSlugJobsNewRoute =
  AuthenticatedVtcSlugJobsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedVtcSlugJobsRoute,
  } as any)
const AuthenticatedVtcSlugJobsJobIdRoute =
  AuthenticatedVtcSlugJobsJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => AuthenticatedVtcSlugJobsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/download-client': typeof DownloadClientRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/s/$slug': typeof SSlugRoute
  '/discover/$slug': typeof AuthenticatedDiscoverSlugRoute
  '/vtc/$slug': typeof AuthenticatedVtcSlugRouteWithChildren
  '/vtc/$slug/applications': typeof AuthenticatedVtcSlugApplicationsRoute
  '/vtc/$slug/billing': typeof AuthenticatedVtcSlugBillingRoute
  '/vtc/$slug/career': typeof AuthenticatedVtcSlugCareerRoute
  '/vtc/$slug/costs': typeof AuthenticatedVtcSlugCostsRoute
  '/vtc/$slug/documents': typeof AuthenticatedVtcSlugDocumentsRoute
  '/vtc/$slug/drivers': typeof AuthenticatedVtcSlugDriversRoute
  '/vtc/$slug/events': typeof AuthenticatedVtcSlugEventsRoute
  '/vtc/$slug/finance': typeof AuthenticatedVtcSlugFinanceRoute
  '/vtc/$slug/fleet': typeof AuthenticatedVtcSlugFleetRoute
  '/vtc/$slug/jobs': typeof AuthenticatedVtcSlugJobsRouteWithChildren
  '/vtc/$slug/live': typeof AuthenticatedVtcSlugLiveRoute
  '/vtc/$slug/messages': typeof AuthenticatedVtcSlugMessagesRoute
  '/vtc/$slug/settings': typeof AuthenticatedVtcSlugSettingsRoute
  '/vtc/$slug/stats': typeof AuthenticatedVtcSlugStatsRoute
  '/vtc/$slug/telemetry': typeof AuthenticatedVtcSlugTelemetryRoute
  '/vtc/$slug/vehicles': typeof AuthenticatedVtcSlugVehiclesRoute
  '/api/public/jobs/recent': typeof ApiPublicJobsRecentRoute
  '/api/public/messages/list': typeof ApiPublicMessagesListRoute
  '/api/public/messages/send': typeof ApiPublicMessagesSendRoute
  '/api/public/telemetry/ingest': typeof ApiPublicTelemetryIngestRoute
  '/api/public/telemetry/live': typeof ApiPublicTelemetryLiveRoute
  '/api/public/telemetry/livemap': typeof ApiPublicTelemetryLivemapRoute
  '/vtc/$slug/': typeof AuthenticatedVtcSlugIndexRoute
  '/vtc/$slug/jobs/$jobId': typeof AuthenticatedVtcSlugJobsJobIdRoute
  '/vtc/$slug/jobs/new': typeof AuthenticatedVtcSlugJobsNewRoute
  '/vtc/$slug/jobs/': typeof AuthenticatedVtcSlugJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/download-client': typeof DownloadClientRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/s/$slug': typeof SSlugRoute
  '/discover/$slug': typeof AuthenticatedDiscoverSlugRoute
  '/vtc/$slug/applications': typeof AuthenticatedVtcSlugApplicationsRoute
  '/vtc/$slug/billing': typeof AuthenticatedVtcSlugBillingRoute
  '/vtc/$slug/career': typeof AuthenticatedVtcSlugCareerRoute
  '/vtc/$slug/costs': typeof AuthenticatedVtcSlugCostsRoute
  '/vtc/$slug/documents': typeof AuthenticatedVtcSlugDocumentsRoute
  '/vtc/$slug/drivers': typeof AuthenticatedVtcSlugDriversRoute
  '/vtc/$slug/events': typeof AuthenticatedVtcSlugEventsRoute
  '/vtc/$slug/finance': typeof AuthenticatedVtcSlugFinanceRoute
  '/vtc/$slug/fleet': typeof AuthenticatedVtcSlugFleetRoute
  '/vtc/$slug/live': typeof AuthenticatedVtcSlugLiveRoute
  '/vtc/$slug/messages': typeof AuthenticatedVtcSlugMessagesRoute
  '/vtc/$slug/settings': typeof AuthenticatedVtcSlugSettingsRoute
  '/vtc/$slug/stats': typeof AuthenticatedVtcSlugStatsRoute
  '/vtc/$slug/telemetry': typeof AuthenticatedVtcSlugTelemetryRoute
  '/vtc/$slug/vehicles': typeof AuthenticatedVtcSlugVehiclesRoute
  '/api/public/jobs/recent': typeof ApiPublicJobsRecentRoute
  '/api/public/messages/list': typeof ApiPublicMessagesListRoute
  '/api/public/messages/send': typeof ApiPublicMessagesSendRoute
  '/api/public/telemetry/ingest': typeof ApiPublicTelemetryIngestRoute
  '/api/public/telemetry/live': typeof ApiPublicTelemetryLiveRoute
  '/api/public/telemetry/livemap': typeof ApiPublicTelemetryLivemapRoute
  '/vtc/$slug': typeof AuthenticatedVtcSlugIndexRoute
  '/vtc/$slug/jobs/$jobId': typeof AuthenticatedVtcSlugJobsJobIdRoute
  '/vtc/$slug/jobs/new': typeof AuthenticatedVtcSlugJobsNewRoute
  '/vtc/$slug/jobs': typeof AuthenticatedVtcSlugJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/download-client': typeof DownloadClientRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/s/$slug': typeof SSlugRoute
  '/_authenticated/discover/$slug': typeof AuthenticatedDiscoverSlugRoute
  '/_authenticated/vtc/$slug': typeof AuthenticatedVtcSlugRouteWithChildren
  '/_authenticated/vtc/$slug/applications': typeof AuthenticatedVtcSlugApplicationsRoute
  '/_authenticated/vtc/$slug/billing': typeof AuthenticatedVtcSlugBillingRoute
  '/_authenticated/vtc/$slug/career': typeof AuthenticatedVtcSlugCareerRoute
  '/_authenticated/vtc/$slug/costs': typeof AuthenticatedVtcSlugCostsRoute
  '/_authenticated/vtc/$slug/documents': typeof AuthenticatedVtcSlugDocumentsRoute
  '/_authenticated/vtc/$slug/drivers': typeof AuthenticatedVtcSlugDriversRoute
  '/_authenticated/vtc/$slug/events': typeof AuthenticatedVtcSlugEventsRoute
  '/_authenticated/vtc/$slug/finance': typeof AuthenticatedVtcSlugFinanceRoute
  '/_authenticated/vtc/$slug/fleet': typeof AuthenticatedVtcSlugFleetRoute
  '/_authenticated/vtc/$slug/jobs': typeof AuthenticatedVtcSlugJobsRouteWithChildren
  '/_authenticated/vtc/$slug/live': typeof AuthenticatedVtcSlugLiveRoute
  '/_authenticated/vtc/$slug/messages': typeof AuthenticatedVtcSlugMessagesRoute
  '/_authenticated/vtc/$slug/settings': typeof AuthenticatedVtcSlugSettingsRoute
  '/_authenticated/vtc/$slug/stats': typeof AuthenticatedVtcSlugStatsRoute
  '/_authenticated/vtc/$slug/telemetry': typeof AuthenticatedVtcSlugTelemetryRoute
  '/_authenticated/vtc/$slug/vehicles': typeof AuthenticatedVtcSlugVehiclesRoute
  '/api/public/jobs/recent': typeof ApiPublicJobsRecentRoute
  '/api/public/messages/list': typeof ApiPublicMessagesListRoute
  '/api/public/messages/send': typeof ApiPublicMessagesSendRoute
  '/api/public/telemetry/ingest': typeof ApiPublicTelemetryIngestRoute
  '/api/public/telemetry/live': typeof ApiPublicTelemetryLiveRoute
  '/api/public/telemetry/livemap': typeof ApiPublicTelemetryLivemapRoute
  '/_authenticated/vtc/$slug/': typeof AuthenticatedVtcSlugIndexRoute
  '/_authenticated/vtc/$slug/jobs/$jobId': typeof AuthenticatedVtcSlugJobsJobIdRoute
  '/_authenticated/vtc/$slug/jobs/new': typeof AuthenticatedVtcSlugJobsNewRoute
  '/_authenticated/vtc/$slug/jobs/': typeof AuthenticatedVtcSlugJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo'
    | '/download-client'
    | '/sitemap.xml'
    | '/app'
    | '/profile'
    | '/s/$slug'
    | '/discover/$slug'
    | '/vtc/$slug'
    | '/vtc/$slug/applications'
    | '/vtc/$slug/billing'
    | '/vtc/$slug/career'
    | '/vtc/$slug/costs'
    | '/vtc/$slug/documents'
    | '/vtc/$slug/drivers'
    | '/vtc/$slug/events'
    | '/vtc/$slug/finance'
    | '/vtc/$slug/fleet'
    | '/vtc/$slug/jobs'
    | '/vtc/$slug/live'
    | '/vtc/$slug/messages'
    | '/vtc/$slug/settings'
    | '/vtc/$slug/stats'
    | '/vtc/$slug/telemetry'
    | '/vtc/$slug/vehicles'
    | '/api/public/jobs/recent'
    | '/api/public/messages/list'
    | '/api/public/messages/send'
    | '/api/public/telemetry/ingest'
    | '/api/public/telemetry/live'
    | '/api/public/telemetry/livemap'
    | '/vtc/$slug/'
    | '/vtc/$slug/jobs/$jobId'
    | '/vtc/$slug/jobs/new'
    | '/vtc/$slug/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo'
    | '/download-client'
    | '/sitemap.xml'
    | '/app'
    | '/profile'
    | '/s/$slug'
    | '/discover/$slug'
    | '/vtc/$slug/applications'
    | '/vtc/$slug/billing'
    | '/vtc/$slug/career'
    | '/vtc/$slug/costs'
    | '/vtc/$slug/documents'
    | '/vtc/$slug/drivers'
    | '/vtc/$slug/events'
    | '/vtc/$slug/finance'
    | '/vtc/$slug/fleet'
    | '/vtc/$slug/live'
    | '/vtc/$slug/messages'
    | '/vtc/$slug/settings'
    | '/vtc/$slug/stats'
    | '/vtc/$slug/telemetry'
    | '/vtc/$slug/vehicles'
    | '/api/public/jobs/recent'
    | '/api/public/messages/list'
    | '/api/public/messages/send'
    | '/api/public/telemetry/ingest'
    | '/api/public/telemetry/live'
    | '/api/public/telemetry/livemap'
    | '/vtc/$slug'
    | '/vtc/$slug/jobs/$jobId'
    | '/vtc/$slug/jobs/new'
    | '/vtc/$slug/jobs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demo'
    | '/download-client'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/_authenticated/profile'
    | '/s/$slug'
    | '/_authenticated/discover/$slug'
    | '/_authenticated/vtc/$slug'
    | '/_authenticated/vtc/$slug/applications'
    | '/_authenticated/vtc/$slug/billing'
    | '/_authenticated/vtc/$slug/career'
    | '/_authenticated/vtc/$slug/costs'
    | '/_authenticated/vtc/$slug/documents'
    | '/_authenticated/vtc/$slug/drivers'
    | '/_authenticated/vtc/$slug/events'
    | '/_authenticated/vtc/$slug/finance'
    | '/_authenticated/vtc/$slug/fleet'
    | '/_authenticated/vtc/$slug/jobs'
    | '/_authenticated/vtc/$slug/live'
    | '/_authenticated/vtc/$slug/messages'
    | '/_authenticated/vtc/$slug/settings'
    | '/_authenticated/vtc/$slug/stats'
    | '/_authenticated/vtc/$slug/telemetry'
    | '/_authenticated/vtc/$slug/vehicles'
    | '/api/public/jobs/recent'
    | '/api/public/messages/list'
    | '/api/public/messages/send'
    | '/api/public/telemetry/ingest'
    | '/api/public/telemetry/live'
    | '/api/public/telemetry/livemap'
    | '/_authenticated/vtc/$slug/'
    | '/_authenticated/vtc/$slug/jobs/$jobId'
    | '/_authenticated/vtc/$slug/jobs/new'
    | '/_authenticated/vtc/$slug/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRoute
  DownloadClientRoute: typeof DownloadClientRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SSlugRoute: typeof SSlugRoute
  ApiPublicJobsRecentRoute: typeof ApiPublicJobsRecentRoute
  ApiPublicMessagesListRoute: typeof ApiPublicMessagesListRoute
  ApiPublicMessagesSendRoute: typeof ApiPublicMessagesSendRoute
  ApiPublicTelemetryIngestRoute: typeof ApiPublicTelemetryIngestRoute
  ApiPublicTelemetryLiveRoute: typeof ApiPublicTelemetryLiveRoute
  ApiPublicTelemetryLivemapRoute: typeof ApiPublicTelemetryLivemapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download-client': {
      id: '/download-client'
      path: '/download-client'
      fullPath: '/download-client'
      preLoaderRoute: typeof DownloadClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vtc/$slug': {
      id: '/_authenticated/vtc/$slug'
      path: '/vtc/$slug'
      fullPath: '/vtc/$slug'
      preLoaderRoute: typeof AuthenticatedVtcSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover/$slug': {
      id: '/_authenticated/discover/$slug'
      path: '/discover/$slug'
      fullPath: '/discover/$slug'
      preLoaderRoute: typeof AuthenticatedDiscoverSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vtc/$slug/': {
      id: '/_authenticated/vtc/$slug/'
      path: '/'
      fullPath: '/vtc/$slug/'
      preLoaderRoute: typeof AuthenticatedVtcSlugIndexRouteImport
      parentRoute: typeof AuthenticatedVtcSlugRoute
    }
    '/api/public/telemetry/livemap': {
      id: '/api/public/telemetry/livemap'
      path: '/api/public/telemetry/livemap'
      fullPath: '/api/public/telemetry/livemap'
      preLoaderRoute: typeof ApiPublicTelemetryLivemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telemetry/live': {
      id: '/api/public/telemetry/live'
      path: '/api/public/telemetry/live'
      fullPath: '/api/public/telemetry/live'
      preLoaderRoute: typeof ApiPublicTelemetryLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telemetry/ingest': {
      id: '/api/public/telemetry/ingest'
      path: '/api/public/telemetry/ingest'
      fullPath: '/api/public/telemetry/ingest'
      preLoaderRoute: typeof ApiPublicTelemetryIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/messages/send': {
      id: '/api/public/messages/send'
      path: '/api/public/messages/send'
      fullPath: '/api/public/messages/send'
      preLoaderRoute: typeof ApiPublicMessagesSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/messages/list': {
      id: '/api/public/messages/list'
      path: '/api/public/messages/list'
      fullPath: '/api/public/messages/list'
      preLoaderRoute: typeof ApiPublicMessagesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/recent': {
      id: '/api/public/jobs/recent'
      path: '/api/public/jobs/recent'
      fullPath: '/api/public/jobs/recent'
      preLoaderRoute: typeof ApiPublicJobsRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vtc/$slug/vehicles': {
      id: '/_authenticated/vtc/$slug/vehicles'
      path: '/vehicles'
      fullPath: '/vtc/$slug/vehicles'
      preLoaderRoute: typeof AuthenticatedVtcSlugVehiclesRouteImport
      parentRoute: typeof AuthenticatedVtcSlugRoute
    }
    '/_authenticated/vtc/$slug/telemetry': {
      id: '/_authenticated/vtc/$slug/telemetry'
      path: '/telemetry'
      fullPath: '/vtc/$slug/telemetry'
      preLoaderRoute: typeof AuthenticatedVtcSlugTelemetryRouteImport
      parentRoute: typeof AuthenticatedVtcSlugRoute
    }
    '/_authenticated/vtc/$slug/stats': {
      id: '/_authenticated/vtc/$slug/stats'
      path: '/stats'
      fullPath: '/vtc/$slug/stats'
      preLoaderRoute: typeof AuthenticatedVtcSlugStatsRouteImport
      parentRoute: typeof AuthenticatedVtcSlugRoute
    }
    '/_authenticated/vtc/$slug/settings': {
      id: '/_authenticated/vtc/$slug/settings'
      path: '/settings'
      fullPath: '/vtc/$slug/settings'
      preLoaderRoute: typeof AuthenticatedVtcSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedVtcSlugRoute
    }
    '/_authenticated/vtc/$slug/messages': {
      id: '/_authenticated/vtc/$slug/messages'
      path: '/messages'
      fullPath: '/vtc/$slug/messages'
      preLoaderRoute: typeof AuthenticatedVtcSlugMessagesRouteImport
      parentRoute: typeof AuthenticatedVtcSlugRoute
    }
    '/_authenticated/vtc/$slug/live': {
      id: '/_authenticated/vtc/$slug/live'
      path: '/live'
      fullPath: '/vtc/$slug/live'
      preLoaderRoute: typeof AuthenticatedVtcSlugLiveRouteImport
      parentRoute: typeof AuthenticatedVtcSlugRoute
    }
    '/_authenticated/vtc/$slug/jobs': {
      id: '/_authenticated/vtc/$slug/jobs'
      path: '/jobs'
      fullPath: '/vtc/$slug/jobs'
      preLoaderRoute: typeof AuthenticatedVtcSlugJobsRouteImport
      parentRoute: typeof AuthenticatedVtcSlugRoute
    }
    '/_authenticated/vtc/$slug/fleet': {
      id: '/_authenticated/vtc/$slug/fleet'
      path: '/fleet'
      fullPath: '/vtc/$slug/fleet'
      preLoaderRoute: typeof AuthenticatedVtcSlugFleetRouteImport
      parentRoute: typeof AuthenticatedVtcSlugRoute
    }
    '/_authenticated/vtc/$slug/finance': {
      id: '/_authenticated/vtc/$slug/finance'
      path: '/finance'
      fullPath: '/vtc/$slug/finance'
      preLoaderRoute: typeof AuthenticatedVtcSlugFinanceRouteImport
      parentRoute: typeof AuthenticatedVtcSlugRoute
    }
    '/_authenticated/vtc/$slug/events': {
      id: '/_authenticated/vtc/$slug/events'
      path: '/events'
      fullPath: '/vtc/$slug/events'
      preLoaderRoute: typeof AuthenticatedVtcSlugEventsRouteImport
      parentRoute: typeof AuthenticatedVtcSlugRoute
    }
    '/_authenticated/vtc/$slug/drivers': {
      id: '/_authenticated/vtc/$slug/drivers'
      path: '/drivers'
      fullPath: '/vtc/$slug/drivers'
      preLoaderRoute: typeof AuthenticatedVtcSlugDriversRouteImport
      parentRoute: typeof AuthenticatedVtcSlugRoute
    }
    '/_authenticated/vtc/$slug/documents': {
      id: '/_authenticated/vtc/$slug/documents'
      path: '/documents'
      fullPath: '/vtc/$slug/documents'
      preLoaderRoute: typeof AuthenticatedVtcSlugDocumentsRouteImport
      parentRoute: typeof AuthenticatedVtcSlugRoute
    }
    '/_authenticated/vtc/$slug/costs': {
      id: '/_authenticated/vtc/$slug/costs'
      path: '/costs'
      fullPath: '/vtc/$slug/costs'
      preLoaderRoute: typeof AuthenticatedVtcSlugCostsRouteImport
      parentRoute: typeof AuthenticatedVtcSlugRoute
    }
    '/_authenticated/vtc/$slug/career': {
      id: '/_authenticated/vtc/$slug/career'
      path: '/career'
      fullPath: '/vtc/$slug/career'
      preLoaderRoute: typeof AuthenticatedVtcSlugCareerRouteImport
      parentRoute: typeof AuthenticatedVtcSlugRoute
    }
    '/_authenticated/vtc/$slug/billing': {
      id: '/_authenticated/vtc/$slug/billing'
      path: '/billing'
      fullPath: '/vtc/$slug/billing'
      preLoaderRoute: typeof AuthenticatedVtcSlugBillingRouteImport
      parentRoute: typeof AuthenticatedVtcSlugRoute
    }
    '/_authenticated/vtc/$slug/applications': {
      id: '/_authenticated/vtc/$slug/applications'
      path: '/applications'
      fullPath: '/vtc/$slug/applications'
      preLoaderRoute: typeof AuthenticatedVtcSlugApplicationsRouteImport
      parentRoute: typeof AuthenticatedVtcSlugRoute
    }
    '/_authenticated/vtc/$slug/jobs/': {
      id: '/_authenticated/vtc/$slug/jobs/'
      path: '/'
      fullPath: '/vtc/$slug/jobs/'
      preLoaderRoute: typeof AuthenticatedVtcSlugJobsIndexRouteImport
      parentRoute: typeof AuthenticatedVtcSlugJobsRoute
    }
    '/_authenticated/vtc/$slug/jobs/new': {
      id: '/_authenticated/vtc/$slug/jobs/new'
      path: '/new'
      fullPath: '/vtc/$slug/jobs/new'
      preLoaderRoute: typeof AuthenticatedVtcSlugJobsNewRouteImport
      parentRoute: typeof AuthenticatedVtcSlugJobsRoute
    }
    '/_authenticated/vtc/$slug/jobs/$jobId': {
      id: '/_authenticated/vtc/$slug/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/vtc/$slug/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedVtcSlugJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedVtcSlugJobsRoute
    }
  }
}

interface AuthenticatedVtcSlugJobsRouteChildren {
  AuthenticatedVtcSlugJobsJobIdRoute: typeof AuthenticatedVtcSlugJobsJobIdRoute
  AuthenticatedVtcSlugJobsNewRoute: typeof AuthenticatedVtcSlugJobsNewRoute
  AuthenticatedVtcSlugJobsIndexRoute: typeof AuthenticatedVtcSlugJobsIndexRoute
}

const AuthenticatedVtcSlugJobsRouteChildren: AuthenticatedVtcSlugJobsRouteChildren =
  {
    AuthenticatedVtcSlugJobsJobIdRoute: AuthenticatedVtcSlugJobsJobIdRoute,
    AuthenticatedVtcSlugJobsNewRoute: AuthenticatedVtcSlugJobsNewRoute,
    AuthenticatedVtcSlugJobsIndexRoute: AuthenticatedVtcSlugJobsIndexRoute,
  }

const AuthenticatedVtcSlugJobsRouteWithChildren =
  AuthenticatedVtcSlugJobsRoute._addFileChildren(
    AuthenticatedVtcSlugJobsRouteChildren,
  )

interface AuthenticatedVtcSlugRouteChildren {
  AuthenticatedVtcSlugApplicationsRoute: typeof AuthenticatedVtcSlugApplicationsRoute
  AuthenticatedVtcSlugBillingRoute: typeof AuthenticatedVtcSlugBillingRoute
  AuthenticatedVtcSlugCareerRoute: typeof AuthenticatedVtcSlugCareerRoute
  AuthenticatedVtcSlugCostsRoute: typeof AuthenticatedVtcSlugCostsRoute
  AuthenticatedVtcSlugDocumentsRoute: typeof AuthenticatedVtcSlugDocumentsRoute
  AuthenticatedVtcSlugDriversRoute: typeof AuthenticatedVtcSlugDriversRoute
  AuthenticatedVtcSlugEventsRoute: typeof AuthenticatedVtcSlugEventsRoute
  AuthenticatedVtcSlugFinanceRoute: typeof AuthenticatedVtcSlugFinanceRoute
  AuthenticatedVtcSlugFleetRoute: typeof AuthenticatedVtcSlugFleetRoute
  AuthenticatedVtcSlugJobsRoute: typeof AuthenticatedVtcSlugJobsRouteWithChildren
  AuthenticatedVtcSlugLiveRoute: typeof AuthenticatedVtcSlugLiveRoute
  AuthenticatedVtcSlugMessagesRoute: typeof AuthenticatedVtcSlugMessagesRoute
  AuthenticatedVtcSlugSettingsRoute: typeof AuthenticatedVtcSlugSettingsRoute
  AuthenticatedVtcSlugStatsRoute: typeof AuthenticatedVtcSlugStatsRoute
  AuthenticatedVtcSlugTelemetryRoute: typeof AuthenticatedVtcSlugTelemetryRoute
  AuthenticatedVtcSlugVehiclesRoute: typeof AuthenticatedVtcSlugVehiclesRoute
  AuthenticatedVtcSlugIndexRoute: typeof AuthenticatedVtcSlugIndexRoute
}

const AuthenticatedVtcSlugRouteChildren: AuthenticatedVtcSlugRouteChildren = {
  AuthenticatedVtcSlugApplicationsRoute: AuthenticatedVtcSlugApplicationsRoute,
  AuthenticatedVtcSlugBillingRoute: AuthenticatedVtcSlugBillingRoute,
  AuthenticatedVtcSlugCareerRoute: AuthenticatedVtcSlugCareerRoute,
  AuthenticatedVtcSlugCostsRoute: AuthenticatedVtcSlugCostsRoute,
  AuthenticatedVtcSlugDocumentsRoute: AuthenticatedVtcSlugDocumentsRoute,
  AuthenticatedVtcSlugDriversRoute: AuthenticatedVtcSlugDriversRoute,
  AuthenticatedVtcSlugEventsRoute: AuthenticatedVtcSlugEventsRoute,
  AuthenticatedVtcSlugFinanceRoute: AuthenticatedVtcSlugFinanceRoute,
  AuthenticatedVtcSlugFleetRoute: AuthenticatedVtcSlugFleetRoute,
  AuthenticatedVtcSlugJobsRoute: AuthenticatedVtcSlugJobsRouteWithChildren,
  AuthenticatedVtcSlugLiveRoute: AuthenticatedVtcSlugLiveRoute,
  AuthenticatedVtcSlugMessagesRoute: AuthenticatedVtcSlugMessagesRoute,
  AuthenticatedVtcSlugSettingsRoute: AuthenticatedVtcSlugSettingsRoute,
  AuthenticatedVtcSlugStatsRoute: AuthenticatedVtcSlugStatsRoute,
  AuthenticatedVtcSlugTelemetryRoute: AuthenticatedVtcSlugTelemetryRoute,
  AuthenticatedVtcSlugVehiclesRoute: AuthenticatedVtcSlugVehiclesRoute,
  AuthenticatedVtcSlugIndexRoute: AuthenticatedVtcSlugIndexRoute,
}

const AuthenticatedVtcSlugRouteWithChildren =
  AuthenticatedVtcSlugRoute._addFileChildren(AuthenticatedVtcSlugRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedDiscoverSlugRoute: typeof AuthenticatedDiscoverSlugRoute
  AuthenticatedVtcSlugRoute: typeof AuthenticatedVtcSlugRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedDiscoverSlugRoute: AuthenticatedDiscoverSlugRoute,
  AuthenticatedVtcSlugRoute: AuthenticatedVtcSlugRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRoute,
  DownloadClientRoute: DownloadClientRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SSlugRoute: SSlugRoute,
  ApiPublicJobsRecentRoute: ApiPublicJobsRecentRoute,
  ApiPublicMessagesListRoute: ApiPublicMessagesListRoute,
  ApiPublicMessagesSendRoute: ApiPublicMessagesSendRoute,
  ApiPublicTelemetryIngestRoute: ApiPublicTelemetryIngestRoute,
  ApiPublicTelemetryLiveRoute: ApiPublicTelemetryLiveRoute,
  ApiPublicTelemetryLivemapRoute: ApiPublicTelemetryLivemapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
