// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');
    const proxySafeToken = request.headers.get('x-supabase-auth');
    const cookieToken = request.headers
      .get('cookie')
      ?.split(';')
      .map((cookie) => cookie.trim())
      .find((cookie) => cookie.startsWith('vtc_supabase_auth='))
      ?.slice('vtc_supabase_auth='.length);

    if (!authHeader && !proxySafeToken && !cookieToken) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (authHeader && !authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token =
      proxySafeToken ||
      authHeader?.replace('Bearer ', '') ||
      (cookieToken ? decodeURIComponent(cookieToken) : '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    if (token.split('.').length !== 3) {
      throw new Error('Unauthorized: Invalid token');
    }

    let tokenIssuer = '';
    try {
      const payload = JSON.parse(
        Buffer.from(token.split('.')[1], 'base64url').toString('utf8'),
      ) as { iss?: string };
      tokenIssuer = payload.iss ?? '';
    } catch {
      throw new Error('Unauthorized: Invalid token payload');
    }

    if (tokenIssuer && !tokenIssuer.startsWith(SUPABASE_URL)) {
      throw new Error(
        `Unauthorized: Supabase project mismatch (${new URL(tokenIssuer).hostname} instead of ${new URL(SUPABASE_URL).hostname})`,
      );
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    // Validate the bearer token against the Auth server. Unlike getClaims(),
    // this also works reliably when a project still uses a symmetric JWT
    // signing secret or the runtime cannot use the project's JWKS endpoint.
    const { data, error } = await supabase.auth.getUser(token);
    if (error || !data.user) {
      throw new Error(`Unauthorized: Invalid token${error?.message ? ` (${error.message})` : ''}`);
    }

    if (!data.user.id) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    return next({
      context: {
        supabase,
        userId: data.user.id,
        claims: {
          sub: data.user.id,
          email: data.user.email,
          role: data.user.role,
          user_metadata: data.user.user_metadata,
          app_metadata: data.user.app_metadata,
        },
      },
    });
  },
);
