// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token

    // Plesk/Passenger may remove custom authentication headers before the
    // request reaches the Node process. Keep a same-site cookie fallback in
    // sync with the browser session so server functions can still authenticate.
    if (token) {
      document.cookie = `vtc_supabase_auth=${encodeURIComponent(token)}; Path=/; Max-Age=3600; SameSite=Lax; Secure`
    } else {
      document.cookie = 'vtc_supabase_auth=; Path=/; Max-Age=0; SameSite=Lax; Secure'
    }

    return next({
      headers: token
        ? {
            Authorization: `Bearer ${token}`,
            // Some reverse proxies strip Authorization before forwarding to Node.
            'X-Supabase-Auth': token,
          }
        : {},
    })
  },
)
